### PR TITLE
add data.md

### PR DESCRIPTION
**Pull request by NicolasMahe**
add data.md to centralize what id we give to resources

@gopherquiv please continue to add id and resources

### CODE REVIEW

**Comment by NicolasMahe** [comment]
One feedback I would give about this ID to improve the system:
We should NOT use incremented id. We should have a nice format for the index.
Example for the image ids: `animal id` + `skin id`
If Bull has id `1` and Diamond has id `3`, then the image id would be `13`.

We can also force each id on 2 digits to be able to add more than 10 skins. In the previous example, the image id would be `0103`

@gopherquiv what do you think?

**Comment by gopherquiv** [comment]
I am not sure what ID implementation would be good. If there's no critical problem with current implementation, I would like to go with current implementation.

Btw, here's description about meta
```
Color is skin color.
Story is provided by minter.
Whitelisted coins will be determined along with mint price for selecting that coin.
lockDuration possible values are 6, 12 months and 1200 months (100 year - permanent).
```

**Comment by antho1404** [comment]
This looks good, it will help a lot.

Side note: I like the idea to combine the different id into a single one for optimization, I don't like the idea of concatenation but in the same direction we could use bit fields but that would make it complicated and I agree that the current implementation is good enough for now

**Comment by NicolasMahe** [comment]
> @NicolasMahe do you have anything to add here?

looking very good. i'm merging.

**Pull request merged**
